### ISSUE TITLE
Missing TAM codes

### ISSUE THREAD

**Issue by AllanColeman** [mce-scarto/TAM-Viewer#5]
“TR6105_A”: “Danger Area when in use”,
TR6106_A Special Restricted Area
TR6115_A Impact Area A Air Weapons Target
TR6201_L Main Tracked Route
TR6202_P Tank Crossing
TR6205_P Sentry Post
TR6304_P Battle Run
TR6405_P Range Arc Marker
TR6502_P Tank Harbour Area
TR6503_P Medical RV and first aid Station
TR6505_P Water Supply Point
TR6507_P Wash Point for Tracked Vehicles
TR6602_P Helicopter Landing Area
TR6603_P Heliport
TR6611_A_Miscellaneous Area
TR6612_ P Meteo Station
TR6700_P Named Location

**Comment by DenisCarriere** [comment]
Added all features
